org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -Dorg.gradle.internal.http.connectionTimeout=180000 -Dorg.gradle.internal.http.socketTimeout=180000
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false

